### ISSUE TITLE
Support node16 in self-hosted runners

### ISSUE THREAD

**Issue by maduq1** [tool3/bump#16]
Hi, we use your tool since some months ago in a self-hosted Linux runner and it works like a charm. But we had to upgrade the node version to 16 because some other deprecations. We also received a notice saying node12 is going EOL, so it won't be supported anymore. 

From what I see in the code, it should be just a matter of changing the node version in the workflow definition, but I am not that familiar with development of this kind of tool to be sure everything else will work. In any case, I will try to take a look myself.

On the while, could you please check it? Thanks in advance!

**Comment by tool3** [comment]
@maduq1 first things first - thank you ! I am so glad to hear that it's working for you and that you are using it regularly ! 

secondly, the PR has some whitespace formatting on the README for some reason, just FYI. 

Thanks !

**Comment by maduq1** [comment]
Thank you so much for having a look! Please let me know when it's released and can be used 🙏  (and sorry again for the wrong whitespacing)

**Comment by tool3** [comment]
@maduq1 https://github.com/tool3/bump/releases/tag/v1.1.7 released ! 

also I just wanted to let you know that you can always use the `master` version by pointing to `@tool3/bump@master` 😇
