### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by styfrombrest** [tool3/bump#22]
Hi!
I've noticed deprecation warnings using bump-version action:

`[bump-version] Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: tool3/bump@v1.1.9. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

`[bump-version] The 'set-output' command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

Is there any plans to upgrade the action to use more fresh version of Node?
Thanks.

**Comment by tool3** [comment]
@styfrombrest absolutely.

I’ll upgrade to the latest node and update this issue once it’s released.

Should be ready by EOW.
